name: Release Reminder

on:
  schedule:
    - cron: '45 0 1 * *'
  workflow_dispatch: {}

jobs:
  reminder:
    name: Reminder
    runs-on: ubuntu-22.04
    steps:
      - name: Get Month
        id: month
        run: |
          echo "month=$(date +%b)" >> "${GITHUB_OUTPUT}"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CF_BOT_GITHUB_TOKEN }}
          ref: develop
          fetch-depth: 0

      - name: Get Latest Version
        id: latest-version
        run: |
          echo "val=$(git describe --abbrev=0 --tag)" >> "${GITHUB_OUTPUT}"

      - name: PHP specific task
        id: php-specific
        if: github.repository == 'cloudfoundry/php-buildpack'
        run: |
          echo 'task=* Bump PHP modules. See [doc](https://github.com/cloudfoundry/buildpacks-ci/tree/master/scripts/php-modules#pre-buildpack-release-task)' >> "${GITHUB_OUTPUT}"

      - name: File Issue
        id: file-issue
        uses: paketo-buildpacks/github-config/actions/issue/file@main
        with:
          token: ${{ secrets.CF_BOT_GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          issue_title: "Release: ${{ github.event.repository.name }} (${{ steps.month.outputs.month }})"
          issue_body: |
            Release reminder for ${{ github.event.repository.name }}

            ${{ steps.php-specific.outputs.task }}
            * See [diff from latest version]("https://github.com/${{ github.repository }}/compare/${{ steps.latest-version.outputs.val }}..develop") and validate if a release is required.
            * Make sure the latest commit on `develop` has passed tests on the [CI](https://buildpacks.ci.cf-app.com/teams/main/pipelines/${{ github.event.repository.name }})
            * Refer [release instructions](https://github.com/pivotal-cf/tanzu-buildpacks/wiki/Releasing-CF-Buildpacks). (private link)

      - name: Add issue to project
        id: issue-to-proj
        uses: paketo-buildpacks/github-config/actions/issue/add-to-project@main
        with:
          # CF buildpacks project - https://github.com/orgs/cloudfoundry/projects/37
          project-org: cloudfoundry
          project-num: 37
          field-name: Workstream
          option-name: Release Train
          issue-node-id: ${{ steps.file-issue.outputs.node-id }}
          token: ${{ secrets.CF_BOT_GITHUB_TOKEN }}
